#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit-dev.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://tcpr.ca/files/craftbukkit/craftbukkit-latest.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

